### PR TITLE
fixes pep8 warnings in docs/conf.py

### PR DESCRIPTION
**Pull request by staranjeet**
This PR fixes the pep8 warnings in docs/conf.py

### CODE REVIEW

**Comment by mbi** [comment]
geez, that's an auto-generated file no one ever reads, but hey thank you :)

**Comment by staranjeet** [comment]
there are other files also, where pep8 warnings are there. I am fixing those also

**Comment by mbi** [comment]
I'm deliberately ignoring stuff, because I think we should have a pragmatic approach to pep8  https://github.com/mbi/django-simple-captcha/blob/master/.pep8

**Comment by staranjeet** [comment]
my bad, i didn't looked into E501 being ignored. The next PR will fix this

**Comment by staranjeet** [comment]
most of the warnings are of E501.

**Comment by mbi** [comment]
Thank you. Do you think it's bad to ignore E501? I mean no one has been coding on a 80 cols terminal for 20 years, what's the point.

**Comment by staranjeet** [comment]
no its not bad. Point is I overlooked the configuration. There are cases where a project uses 80 cols.

**Pull request merged**
