### PR TITLE
fix link to documentation

### PR DESCRIPTION
**Pull request by 1vank1n**
Also fix link in description of project.

Good luck!

### CODE REVIEW

**Comment by mbi** [comment]
Thanks, but what's wrong with the current link?

**Comment by 1vank1n** [comment]
@mbi, hi!

Current link show page with: "Fail.  Check back in a bit!"

**Comment by mbi** [comment]
You're right, how strange, it was working for me this morning!
Anyway, thank you!

**Comment by 1vank1n** [comment]
@mbi no problem! Thanks for your project!

**Pull request merged**
